version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - kafka
      - postgresql
    env_file:
      - ./.env
    networks:
      - fastapi_listener_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    networks:
      - fastapi_listener_network

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      - fastapi_listener_network

  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Somepass_123
      - POSTGRES_DB=fastapi_listener_db
    networks:
      - fastapi_listener_network

  data_consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      - kafka
      - postgresql
    working_dir: /app
    env_file:
      - ./.env
    networks:
      - fastapi_listener_network
    command: python consumer.py

networks:
  fastapi_listener_network:
